apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: lento
  name: meu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/fabio/Desktop/Estudos/LinuxTips/PICK/PICK2024/Descomplicando_Kubernetes/day-6/mnt/data/ 
  storageClassName: giropops

