apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    fruta: goxiba
  name: nginx-deployment
  namespace: default
spec:
  replicas: 14
  revisionHistoryLimit: 10
  selector: 
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        resources:
          limits:
            cpu: 0.9
            memory: 256Mi
          requests:
            cpu: 0.4
            memory: 64Mi
